from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from self_healing_loop import (
    FAULT_CATEGORIES,
    ExceptionLedger,
    RepairConfig,
    SelfHealingOrchestrator,
    audit_neutrality,
    audit_test_integrity,
    audit_unsafe,
    fault_injection_plan,
    inject_fault,
    normalize_diagnostic,
    run_fault_injection_campaign,
    rust_test_inventory,
    snapshot,
    tree_digest,
    unsafe_inventory,
    validate_integrity_summary,
    validate_repair_ir,
)
from loopforge_runner import main as runner_main


def project(root: Path) -> Path:
    crate = root / "crate"
    (crate / "src").mkdir(parents=True)
    (crate / "tests").mkdir()
    (crate / "Cargo.toml").write_text('[package]\nname="neutral"\nversion="0.1.0"\nedition="2021"\n', encoding="utf-8")
    (crate / "Cargo.lock").write_text("# This file is automatically @generated by Cargo.\nversion = 3\n", encoding="utf-8")
    (crate / "src" / "lib.rs").write_text("pub fn value() -> i32 { 1 }\n", encoding="utf-8")
    (crate / "tests" / "behavior.rs").write_text('#[test]\nfn returns_value() { assert_eq!(neutral::value(), 1); }\n', encoding="utf-8")
    return crate


class SelfHealingContractsTests(unittest.TestCase):
    def test_normalization_and_stale_evidence_validation(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            crate = project(root)
            evidence = root / "compiler.log"
            evidence.write_text("error[E0308]: mismatched types\n --> src/lib.rs:1:28", encoding="utf-8")
            repair_ir = normalize_diagnostic(run_id="run-1", source="compiler", tool="rustc", text=evidence.read_text(), project_root=crate, evidence_path=evidence)
            self.assertEqual(repair_ir["category"], "type_mismatch")
            self.assertEqual(repair_ir["location"]["path"], "src/lib.rs")
            self.assertEqual(validate_repair_ir(repair_ir, run_id="run-1", project_root=crate), [])
            self.assertIn("stale_run_identity", validate_repair_ir(repair_ir, run_id="run-2", project_root=crate))

    def test_test_and_unsafe_integrity(self):
        with tempfile.TemporaryDirectory() as tmp:
            crate = project(Path(tmp))
            before = rust_test_inventory(crate)
            (crate / "tests" / "behavior.rs").write_text("#[test]\nfn returns_value() { assert!(true); }\n", encoding="utf-8")
            failures = audit_test_integrity(before, rust_test_inventory(crate))
            self.assertIn("vacuous_assertion", failures)
            old_unsafe = unsafe_inventory(crate)
            (crate / "src" / "lib.rs").write_text("pub unsafe fn value() -> i32 { 1 }\n", encoding="utf-8")
            self.assertTrue(audit_unsafe(old_unsafe, unsafe_inventory(crate)))

    def test_ledger_distinguishes_dependency_skips(self):
        ledger = ExceptionLedger("run")
        root = ledger.add(kind="timeout", stage="targeted", detail="timeout")
        skipped = ledger.add(kind="dependency", stage="regression", detail="not run", caused_by=root.exception_id)
        self.assertEqual(ledger.deferred(), [root])
        self.assertEqual(skipped.caused_by, root.exception_id)

    def test_fault_matrix_has_three_repetitions_and_all_categories(self):
        plan = fault_injection_plan("run", "a" * 64)
        self.assertEqual(len(plan), len(FAULT_CATEGORIES) * 3)
        self.assertEqual({item["category"] for item in plan}, set(FAULT_CATEGORIES))
        self.assertTrue(all(sum(item["category"] == category for item in plan) == 3 for category in FAULT_CATEGORIES))
        with self.assertRaises(ValueError):
            fault_injection_plan("run", "a" * 64, repetitions=2)

    def test_each_fault_injector_changes_neutral_source(self):
        fixtures = {
            "type_mismatch": "fn main() { let amount: i32 = 1; }",
            "borrow_conflict": "fn main() { let mut values = vec![1]; }",
            "unresolved_symbol": "fn known() {} fn main() { known(); }",
            "return_value": "fn value() -> i32 { return 1; }",
            "state_transition": "fn main() { let mut state = 0; state += 1; }",
            "boundary_off_by_one": "fn f(items: &[i32], index: usize) { if index < items.len() {} }",
        }
        for category, source in fixtures.items():
            with self.subTest(category=category):
                mutated, patch = inject_fault(source, category, 1)
                self.assertNotEqual(mutated, source)
                self.assertIn(f"category={category}", patch)

    def test_fault_campaign_archives_three_verified_repetitions(self):
        with tempfile.TemporaryDirectory() as tmp:
            report = run_fault_injection_campaign(Path(tmp), "run")
            self.assertTrue(report["passed"])
            self.assertEqual(report["attempted_count"], len(FAULT_CATEGORIES) * 3)
            self.assertTrue(all(count == 3 for count in report["category_counts"].values()))
            for record in report["records"]:
                evidence = Path(record["evidence_dir"])
                self.assertTrue((evidence / "injected-defect.patch").is_file())
                self.assertTrue((evidence / "full-regression.log").is_file())

    def test_neutrality_scan_and_branch_audit(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rules.py"
            path.write_text('if project == "forbidden_identity":\n    strategy = "special"\n', encoding="utf-8")
            report = audit_neutrality([path], ["forbidden_identity"])
            self.assertFalse(report["passed"])
            self.assertTrue(report["findings"])
            self.assertTrue(report["branch_findings"])


class OrchestrationTests(unittest.TestCase):
    def make_ir(self, root: Path, crate: Path, run_id: str = "run"):
        evidence = root / "diagnostic.log"
        evidence.write_text("error: expected value\n --> src/lib.rs:1:28", encoding="utf-8")
        return normalize_diagnostic(run_id=run_id, source="targeted-test", tool="cargo", text=evidence.read_text(), project_root=crate, evidence_path=evidence)

    def test_verified_candidate_is_atomically_committed(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            crate = project(root)
            trace = root / "trace"
            repair_ir = self.make_ir(root, crate)

            def provider(task, isolated):
                target = isolated / "src" / "lib.rs"
                target.write_text("pub fn value() -> i32 { 1 }\n// repaired\n", encoding="utf-8")
                return {"applied": True, "patch": "+// repaired"}

            config = RepairConfig(targeted_command=(sys.executable, "-c", "pass"), regression_command=(sys.executable, "-c", "pass"))
            loop = SelfHealingOrchestrator(run_id="run", project_root=crate, trace_dir=trace, provider=provider, config=config)
            self.assertTrue(loop.process(repair_ir))
            loop.final_retry()
            report = loop.publish()
            self.assertIn("repaired", (crate / "src" / "lib.rs").read_text())
            self.assertEqual(report["compliance_status"], "satisfied")
            self.assertEqual(report["validation_failures"], [])

    def test_unrelated_change_is_rejected_then_reported_unresolved(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            crate = project(root)
            original = tree_digest(crate)
            trace = root / "trace"
            repair_ir = self.make_ir(root, crate)

            def provider(task, isolated):
                (isolated / "Cargo.toml").write_text("invalid", encoding="utf-8")
                return {"applied": True, "patch": "bad"}

            config = RepairConfig(max_local_rounds=1, targeted_command=(sys.executable, "-c", "pass"), regression_command=(sys.executable, "-c", "pass"))
            loop = SelfHealingOrchestrator(run_id="run", project_root=crate, trace_dir=trace, provider=provider, config=config)
            self.assertFalse(loop.process(repair_ir))
            loop.final_retry()
            loop.final_retry()
            report = loop.publish()
            self.assertEqual(tree_digest(crate), original)
            self.assertTrue(report["final_retry_executed"])
            self.assertEqual(report["counts"]["unresolved"], 1)
            self.assertEqual(report["execution_status"], "completed")
            self.assertEqual(report["compliance_status"], "not_satisfied")

    def test_provider_exception_degrades_without_escaping(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            crate = project(root)
            repair_ir = self.make_ir(root, crate)

            def provider(task, isolated):
                raise RuntimeError("provider unavailable")

            config = RepairConfig(max_local_rounds=1, targeted_command=(sys.executable, "-c", "pass"), regression_command=(sys.executable, "-c", "pass"))
            loop = SelfHealingOrchestrator(run_id="run", project_root=crate, trace_dir=root / "trace", provider=provider, config=config)
            self.assertFalse(loop.process(repair_ir))
            loop.final_retry()
            report = loop.publish()
            self.assertEqual(report["counts"]["unresolved"], 1)
            self.assertTrue((root / "trace" / "exception-ledger.json").is_file())

    def test_multiple_unresolved_exceptions_remain_individually_reported(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            crate = project(root)

            def provider(task, isolated):
                return {"applied": False, "failure_kind": "generation", "detail": "no candidate"}

            config = RepairConfig(max_local_rounds=1, targeted_command=(sys.executable, "-c", "pass"), regression_command=(sys.executable, "-c", "pass"))
            loop = SelfHealingOrchestrator(run_id="run", project_root=crate, trace_dir=root / "trace", provider=provider, config=config)
            first = self.make_ir(root, crate)
            second_log = root / "second.log"
            second_log.write_text("error: state transition mismatch\n --> src/lib.rs:1:1", encoding="utf-8")
            second = normalize_diagnostic(run_id="run", source="differential", tool="oracle", text=second_log.read_text(), project_root=crate, evidence_path=second_log)
            self.assertFalse(loop.process(first))
            self.assertFalse(loop.process(second))
            loop.final_retry()
            report = loop.publish()
            self.assertEqual(report["counts"]["unresolved"], 2)
            self.assertEqual(len(report["exception_ledger"]["entries"]), 2)

    def test_summary_rejects_stale_and_missing_attempt_evidence(self):
        payload = {"run_id": "run", "counts": {"attempted": 1, "repaired": 1, "deferred": 0, "final_retry_repaired": 0}, "attempts": [{"run_id": "old", "attempt_id": "x", "status": "repaired", "evidence_dir": "missing"}]}
        failures = validate_integrity_summary(payload)
        self.assertTrue(any(item.startswith("stale_attempt") for item in failures))
        self.assertTrue(any(item.startswith("missing_attempt_evidence") for item in failures))

    def test_entrypoint_exception_is_reported_without_process_failure(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            with patch("loopforge_runner.Path.cwd", return_value=root), patch("loopforge_runner.LoopForgeRunner", side_effect=RuntimeError("startup failure")):
                exit_code = runner_main(["--run", "--work-dir", "work", "--log-dir", "logs", "--result-dir", "result"])
            self.assertEqual(exit_code, 0)
            payload = json.loads((root / "logs" / "c-to-rust" / "entrypoint-exception.json").read_text())
            self.assertEqual(payload["compliance_status"], "not_satisfied")
            self.assertTrue((root / "result" / "output.md").is_file())


if __name__ == "__main__":
    unittest.main()
