import copy
import json
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace


RUNTIME = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(RUNTIME))

from rust_project_generation import (  # noqa: E402
    EVIDENCE_FILES,
    GenerationBlocked,
    audit_unsafe,
    build_evidence,
    compute_incremental_dependencies,
    incremental_regenerate,
    load_generation_inputs,
    scan_placeholders,
    summarize_final_repair,
    snapshot_tree,
    validate_candidate,
    write_evidence,
)
from source_analysis import build_complete_analysis, write_complete_analysis  # noqa: E402
from semantic_planning import load_analysis_evidence, write_semantic_plan, build_semantic_plan  # noqa: E402
from c2rust_project_generator import _build_type_index, _render_function, _render_module  # noqa: E402


FIXTURE = Path(__file__).parent / "fixtures" / "flashdb-real-layout"


def _packet(root):
    return SimpleNamespace(metadata={"layout_resolution": {
        "source_dirs": [str(root / "src"), str(root / "inc")],
        "test_dirs": [str(root / "tests")],
    }})


def _legacy(root):
    return {
        "project_root": str(root), "public_apis": ["fdb_kv_set"], "test_files": ["tests/test_flashdb.c"],
        "functions": [
            {"name": "fdb_kv_set", "decl_kind": "prototype", "file": "inc/flashdb.h", "line": 16},
            {"name": "fdb_kv_set", "decl_kind": "definition", "file": "src/flashdb.c", "line": 10},
        ],
    }


def _inputs(trace):
    source = build_complete_analysis(_packet(FIXTURE), _legacy(FIXTURE))
    write_complete_analysis(source, trace)
    plan = build_semantic_plan(load_analysis_evidence(trace), run_id="planning-run")
    write_semantic_plan(plan, trace)
    return load_generation_inputs(trace)


def _project(root):
    project = root / "flashDB_rust"
    (project / "src").mkdir(parents=True)
    (project / "Cargo.toml").write_text(
        '[package]\nname = "flashdb-rust"\nversion = "0.1.0"\nedition = "2021"\nrust-version = "1.70"\n', encoding="utf-8")
    (project / "Cargo.lock").write_text(
        '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "flashdb-rust"\nversion = "0.1.0"\n', encoding="utf-8")
    (project / "src" / "lib.rs").write_text(
        """#![forbid(unsafe_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FdbStatus { Ok, Error }

pub trait StorageIo { fn read(&self, key: &str) -> Option<i32>; fn write(&mut self, key: &str, value: i32) -> bool; }
pub trait FlashPort { fn erase(&mut self, sector: usize) -> bool; }
pub trait ClockPort { fn now(&self) -> u64; }
pub trait LockPort { fn lock(&self) -> bool; fn unlock(&self); }

pub struct FdbBackend<W: FnMut(&str, i32) -> bool> { pub capacity: usize, pub writes: usize, pub write: W }

fn backend_is_valid<W: FnMut(&str, i32) -> bool>(backend: &FdbBackend<W>) -> bool {
    backend.capacity > 0 && backend.writes < backend.capacity
}

pub fn fdb_kv_set<W: FnMut(&str, i32) -> bool>(backend: &mut FdbBackend<W>, key: &str, value: i32) -> FdbStatus {
    if key.is_empty() || !backend_is_valid(backend) { return FdbStatus::Error; }
    if !(backend.write)(key, value) { return FdbStatus::Error; }
    backend.writes += 1;
    FdbStatus::Ok
}
""", encoding="utf-8")
    return project


class RustProjectGenerationTests(unittest.TestCase):
    def test_production_generation_has_no_benchmark_specific_branch(self):
        production = "\n".join(
            (RUNTIME / name).read_text(encoding="utf-8").lower()
            for name in ("rust_project_generation.py", "c2rust_project_generator.py")
        )
        for token in ("flashdb", "kvdb", "tsdb", "fdb_"):
            self.assertNotIn(token, production)

    def test_verified_chain_and_candidate_pass(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); trace = root / "trace"
            inputs = _inputs(trace); project = _project(root)
            result = validate_candidate(project, inputs)
        self.assertTrue(result["passed"], result)
        self.assertEqual(result["metrics"]["public_api_count"], 1)
        self.assertEqual(result["placeholder_findings"], [])
        self.assertEqual({item["source_symbol"] for item in result["implementation_map"]}, {"fdb_kv_set"})

    def test_loader_rejects_missing_stale_and_mixed_evidence(self):
        with tempfile.TemporaryDirectory() as temp:
            trace = Path(temp); _inputs(trace)
            doc = json.loads((trace / "behavior-contracts.json").read_text())
            doc["parent_analysis_run_id"] = "stale"
            (trace / "behavior-contracts.json").write_text(json.dumps(doc))
            with self.assertRaises(GenerationBlocked) as caught:
                load_generation_inputs(trace)
            self.assertTrue(any("planning:" in item or "mixed_planning_identity" in item for item in caught.exception.failures))
            (trace / "type-map.json").unlink()
            with self.assertRaises(GenerationBlocked) as caught:
                load_generation_inputs(trace)
            self.assertTrue(any("missing_analysis_evidence:type-map.json" in item for item in caught.exception.failures))

    def test_missing_api_and_function_are_not_removed_from_denominator(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            source = project / "src" / "lib.rs"
            source.write_text(source.read_text().replace("pub fn fdb_kv_set", "pub fn omitted_set"))
            result = validate_candidate(project, inputs, build=False)
        self.assertFalse(result["checks"]["public_api_coverage_100_percent"])
        self.assertFalse(result["checks"]["unsupported_functions_empty"])

    def test_unresolved_generation_diagnostics_are_reported_at_final_gate(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            unresolved = [{"symbol": "fdb_kv_set", "stage": "final_repair_pass", "reason": "no generic repair pattern matched", "resolved": False}]
            failed = validate_candidate(project, inputs, build=False, generation_diagnostics=unresolved)
            resolved = validate_candidate(project, inputs, build=False, generation_diagnostics=[{**unresolved[0], "resolved": True}])
        self.assertFalse(failed["checks"]["generation_diagnostics_clear"])
        self.assertIn("generation_diagnostics_clear", failed["failures"])
        self.assertEqual(failed["final_repair_summary"]["attempted_count"], 1)
        self.assertEqual(failed["final_repair_summary"]["unresolved_symbols"], ["fdb_kv_set"])
        self.assertTrue(resolved["checks"]["generation_diagnostics_clear"])
        self.assertEqual(resolved["final_repair_summary"]["resolved_symbols"], ["fdb_kv_set"])

    def test_missing_planned_call_edge_is_rejected(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            broken = copy.deepcopy(inputs)
            broken["planning"]["rust-migration-plan.json"]["call_edge_mappings"] = []
            result = validate_candidate(project, broken, build=False)
        self.assertFalse(result["checks"]["module_edges_complete"])

    def test_placeholder_and_vacuous_mutation_are_rejected(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            source = project / "src" / "lib.rs"
            text = source.read_text()
            start = text.index("pub fn fdb_kv_set")
            text = text[:start] + "pub fn fdb_kv_set(_backend: &mut FdbBackend<impl FnMut(&str, i32) -> bool>, _key: &str, _value: i32) -> i32 { 0 }\n"
            source.write_text(text)
            result = validate_candidate(project, inputs, build=False)
        self.assertFalse(result["checks"]["placeholder_scan_clear"])
        self.assertTrue(any(item["kind"] == "constant_success" for item in result["placeholder_findings"]))

    def test_explicit_placeholder_variants_are_detected(self):
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp); (project / "src").mkdir()
            (project / "src" / "lib.rs").write_text('pub fn a() { todo!() }\npub fn b() { unimplemented!() }\npub fn c() { panic!("placeholder") }')
            kinds = {item["kind"] for item in scan_placeholders(project)}
        self.assertEqual(kinds, {"todo_macro", "unimplemented_macro", "placeholder_panic"})

    def test_heuristic_finding_requires_contract_backed_adjudication(self):
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp); (project / "src").mkdir()
            (project / "src" / "lib.rs").write_text("pub fn status() -> i32 { 0 }", encoding="utf-8")
            finding = scan_placeholders(project, {"status"})[0]
            incomplete = scan_placeholders(project, {"status"}, {finding["id"]: {"verdict": "source_semantics_preserved"}})
            resolved = scan_placeholders(project, {"status"}, {finding["id"]: {
                "verdict": "source_semantics_preserved", "contract_id": "contract-1",
                "source_evidence": ["src/status.c:4"], "reason": "the source contract requires zero",
            }})
        self.assertEqual(incomplete[0]["adjudication"], "unresolved")
        self.assertEqual(resolved[0]["adjudication"], "resolved")

    def test_complex_c_assignment_is_repaired_before_fail_closed(self):
        analysis = {"type_table": [{"kind": "struct", "name": "Store", "fields": [{"name": "count", "type": "size_t"}]}]}
        function = {
            "name": "store_reset", "decl_kind": "definition", "translation_status": "translated",
            "file": "src/store.c", "return_type": "int", "module_hint": "store",
            "params": [{"name": "store", "type": "struct Store *"}],
            "body_kind": "state_mutation_then_return",
            "raw_body": "int store_reset(struct Store *store) { store->count = 0; return 0; }",
            "body_value": {"assignments": [{"target": "store->count", "operator": "=", "value": "0"}], "return_expr": "0"},
        }
        rendered, translated = _render_function(function, _build_type_index(analysis))
        self.assertTrue(translated)
        self.assertIn("store: &mut Store", rendered)
        self.assertIn("store.count = 0;", rendered)
        self.assertNotIn("todo!", rendered)

    def test_scalar_output_pointer_is_translated_without_pseudo_return(self):
        function = {
            "name": "read_value", "decl_kind": "definition", "translation_status": "translated",
            "file": "src/io.c", "return_type": "int", "module_hint": "io",
            "params": [{"name": "out", "type": "int *"}, {"name": "value", "type": "int"}],
            "body_kind": "assignment_then_return",
            "raw_body": "int read_value(int *out, int value) { *out = value; return 0; }",
            "body_value": {"assignments": [{"target": "*out", "operator": "=", "value": "value"}], "return_expr": "0"},
        }
        rendered, translated = _render_function(function, {})
        self.assertTrue(translated)
        self.assertIn("out: &mut i32", rendered)
        self.assertIn("*out = value;", rendered)
        self.assertIn("    0", rendered)

    def test_module_generation_records_unresolved_function_without_interrupting(self):
        functions = [
            {
                "name": "ok_value", "decl_kind": "definition", "translation_status": "translated",
                "file": "src/core.c", "line": 3, "return_type": "int", "params": [],
                "body_kind": "return_number", "body_value": "7",
            },
            {
                "name": "hard_value", "decl_kind": "definition", "translation_status": "unsupported",
                "unsupported_reason": "control flow pattern not recognized by the source-driven translator",
                "file": "src/core.c", "line": 8, "return_type": "int", "params": [],
                "body_kind": "unsupported", "raw_body": "if (x) { return 1; } return 0;",
            },
        ]
        module_rs, translated_count, rendered_functions, diagnostics = _render_module("core", functions, [], [], {})
        self.assertIn("pub fn ok_value()", module_rs)
        self.assertNotIn("pub fn hard_value()", module_rs)
        self.assertEqual(translated_count, 1)
        self.assertEqual([item["name"] for item in rendered_functions], ["ok_value"])
        self.assertEqual(diagnostics[0]["symbol"], "hard_value")
        self.assertFalse(diagnostics[0]["resolved"])
        self.assertEqual(summarize_final_repair(diagnostics)["unresolved_symbols"], ["hard_value"])

    def test_final_repair_pass_can_resolve_simple_raw_return(self):
        functions = [{
            "name": "raw_status", "decl_kind": "definition", "translation_status": "unsupported",
            "unsupported_reason": "initial classifier missed raw return",
            "file": "src/status.c", "line": 4, "return_type": "int", "params": [],
            "body_kind": "unsupported", "raw_body": "return 5;",
        }]
        module_rs, translated_count, rendered_functions, diagnostics = _render_module("status", functions, [], [], {})
        self.assertIn("pub fn raw_status() -> i32", module_rs)
        self.assertEqual(translated_count, 1)
        self.assertEqual([item["name"] for item in rendered_functions], ["raw_status"])
        self.assertTrue(diagnostics[0]["resolved"])
        self.assertEqual(summarize_final_repair(diagnostics)["resolved_symbols"], ["raw_status"])

    def test_incremental_dependencies_come_from_verified_plan(self):
        with tempfile.TemporaryDirectory() as temp:
            inputs = _inputs(Path(temp))
            graph = compute_incremental_dependencies(inputs)
        self.assertEqual(graph["flashdb"][0]["module"], "ports")
        self.assertTrue(graph["flashdb"][0]["evidence"])

    def test_unsafe_metric_is_node_based_and_strict(self):
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp); (project / "src").mkdir()
            (project / "src" / "lib.rs").write_text("unsafe fn raw() {}\nfn safe() {}\n")
            failed = audit_unsafe(project)
            key = failed["occurrences"][0]["id"]
            still_failed = audit_unsafe(project, {key: {"necessity": "ffi", "safety_invariant": "valid pointer", "boundary": "raw"}})
            (project / "src" / "lib.rs").write_text("unsafe fn raw() {}\n" + "\n".join(f"fn safe{i}() {{}}" for i in range(10)))
            key = audit_unsafe(project)["occurrences"][0]["id"]
            passed = audit_unsafe(project, {key: {"necessity": "ffi", "safety_invariant": "valid pointer", "boundary": "raw"}})
        self.assertFalse(failed["passed"])
        self.assertFalse(still_failed["passed"])
        self.assertTrue(passed["passed"])
        self.assertLess(passed["ratio"], 0.10)

    def test_zero_unsafe_project_passes_with_nonzero_denominator(self):
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp); (project / "src").mkdir(); (project / "src" / "lib.rs").write_text("pub fn safe() -> i32 { 1 }")
            result = audit_unsafe(project)
        self.assertTrue(result["passed"])
        self.assertGreater(result["item_count"], 0)

    def test_evidence_has_one_identity_and_atomic_missing_artifact_failure(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); trace = root / "trace"; inputs = _inputs(trace); project = _project(root)
            bundle = build_evidence(project, inputs, run_id="generation-run")
            out = root / "out"; write_evidence(bundle, out)
            docs = [json.loads((out / name).read_text()) for name in EVIDENCE_FILES]
            before = {name: (out / name).read_bytes() for name in EVIDENCE_FILES}
            broken = copy.deepcopy(bundle); del broken["artifacts"][EVIDENCE_FILES[0]]
            with self.assertRaises(KeyError): write_evidence(broken, out)
            self.assertEqual({item["run_id"] for item in docs}, {"generation-run"})
            self.assertEqual(before, {name: (out / name).read_bytes() for name in EVIDENCE_FILES})

    def test_stale_lock_file_fails_locked_build_without_publication_claim(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            (project / "Cargo.toml").write_text((project / "Cargo.toml").read_text() + '\n[dependencies]\nserde = "1"\n')
            result = validate_candidate(project, inputs)
        self.assertFalse(result["checks"]["cargo_build_locked_passed"])
        self.assertEqual(result["status"], "BLOCKED_WITH_REPORT")

    def test_incremental_regeneration_preserves_unrelated_hashes(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            (project / "src" / "kvdb.rs").write_text("pub fn marker() -> usize { 1 }\n")
            before = snapshot_tree(project)
            def regenerate(candidate, _closure):
                path = candidate / "src" / "kvdb.rs"; path.write_text(path.read_text().replace("{ 1 }", "{ 2 }"))
            report = incremental_regenerate(project, root / "evidence", inputs, "kvdb", regenerate, build=True)
            after = snapshot_tree(project)
        self.assertTrue(report["passed"])
        self.assertEqual(report["changed_files"], ["src/kvdb.rs"])
        self.assertEqual(before["src/lib.rs"], after["src/lib.rs"])

    def test_incremental_unknown_target_and_boundary_violation_roll_back(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); inputs = _inputs(root / "trace"); project = _project(root)
            before = snapshot_tree(project)
            with self.assertRaises(GenerationBlocked):
                incremental_regenerate(project, root / "evidence", inputs, "missing", lambda *_: None, build=False)
            def violate(candidate, _closure):
                path = candidate / "src" / "lib.rs"; path.write_text(path.read_text() + "\npub fn changed() {}\n")
            (project / "src" / "kvdb.rs").write_text("pub fn marker() -> usize { 1 }\n")
            stable = snapshot_tree(project)
            with self.assertRaises(GenerationBlocked):
                incremental_regenerate(project, root / "evidence", inputs, "kvdb", violate, build=False)
            self.assertEqual(before, {k: v for k, v in stable.items() if k != "src/kvdb.rs"})
            self.assertEqual(stable, snapshot_tree(project))

    def test_incremental_result_is_deterministic_for_same_parent(self):
        def run_once(root):
            inputs = _inputs(root / "trace"); project = _project(root); (project / "src" / "kvdb.rs").write_text("pub fn marker() -> usize { 1 }\n")
            def regenerate(candidate, _closure):
                path = candidate / "src" / "kvdb.rs"; path.write_text("pub fn marker() -> usize { 2 }\n")
            return incremental_regenerate(project, root / "evidence", inputs, "kvdb", regenerate, build=False)
        with tempfile.TemporaryDirectory() as first, tempfile.TemporaryDirectory() as second:
            a = run_once(Path(first)); b = run_once(Path(second))
        for field in ("target_module", "direct_dependencies", "allowed_closure", "allowed_files", "changed_files", "out_of_bounds"):
            self.assertEqual(a[field], b[field])


if __name__ == "__main__":
    unittest.main()
