import copy
import json
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace


RUNTIME = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(RUNTIME))

from rust_project_generation import build_evidence as build_generation_evidence  # noqa: E402
from rust_project_generation import load_generation_inputs, write_evidence as write_generation_evidence  # noqa: E402
from semantic_planning import build_semantic_plan, load_analysis_evidence, write_semantic_plan  # noqa: E402
from source_analysis import build_complete_analysis, write_complete_analysis  # noqa: E402
from test_migration_validation import (  # noqa: E402
    FIXED_MUTATIONS,
    OUTPUT_FILES,
    TestValidationBlocked,
    build_differential_vectors,
    build_evidence,
    build_invariant_test_map,
    build_source_test_map,
    build_state_machine_vectors,
    build_test_ir,
    canonical_counts,
    detect_weakened_assertions,
    execute_differential_vectors,
    load_validation_inputs,
    project_terms_from_inputs,
    run_cargo_tests,
    run_mutation_testing,
    scan_assertions,
    scan_project_customization,
    validate_all,
    write_evidence,
)


FIXTURE = Path(__file__).parent / "fixtures" / "generic-counter"


def _packet(root):
    return SimpleNamespace(metadata={"layout_resolution": {
        "source_dirs": [str(root / "src"), str(root / "inc")],
        "test_dirs": [str(root / "tests")],
    }})


def _legacy(root):
    return {
        "project_root": str(root),
        "public_apis": ["counter_increment"],
        "test_files": ["tests/test_counter.c"],
        "functions": [
            {"name": "counter_increment", "decl_kind": "prototype", "file": "inc/counter.h", "line": 4, "return_type": "int", "params": []},
            {"name": "counter_increment", "decl_kind": "definition", "file": "src/counter.c", "line": 4, "return_type": "int", "params": []},
        ],
    }


def _write_coverage(trace):
    (trace / "01f-test-coverage-map.json").write_text(json.dumps({
        "source_tests": [{
            "file": "tests/test_counter.c",
            "test_names": ["test_counter"],
            "assertions": [{"kind": "macro", "macro": "assert", "expr": "counter_increment((void *)0, 1) == 1"}],
            "referenced_apis": ["counter_increment"],
            "reference_evidence": {"counter_increment": "function_call"},
        }],
        "source_assertions": [{"kind": "macro", "macro": "assert", "expr": "counter_increment((void *)0, 1) == 1"}],
    }, indent=2), encoding="utf-8")
    (trace / "04-test-mapping.json").write_text(json.dumps({"test_mapping": [{
        "source_test": "tests/test_counter.c",
        "rust_test_file": "tests/source_migration.rs",
        "mapping": "source API calls with translated assertions",
        "coverage_level": "semantic_mapped",
        "mapped_apis": ["counter_increment"],
        "unsupported_apis": [],
        "source_assertion_count": 1,
    }]}, indent=2), encoding="utf-8")


def _project(root):
    project = root / "counter_rust"
    (project / "src").mkdir(parents=True)
    (project / "tests").mkdir(parents=True)
    (project / "Cargo.toml").write_text(
        '[package]\nname = "counter-rust"\nversion = "0.1.0"\nedition = "2021"\nrust-version = "1.70"\n\n[lib]\nname = "counter_rust"\npath = "src/lib.rs"\n',
        encoding="utf-8",
    )
    (project / "Cargo.lock").write_text(
        '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "counter-rust"\nversion = "0.1.0"\n',
        encoding="utf-8",
    )
    (project / "src" / "lib.rs").write_text(
        "pub struct CounterState { pub value: i32 }\n"
        "pub fn checked_add(value: i32, amount: i32) -> i32 { value + amount }\n"
        "pub fn counter_increment(state: &mut CounterState, amount: i32) -> i32 { state.value = checked_add(state.value, amount); state.value }\n",
        encoding="utf-8",
    )
    (project / "tests" / "source_migration.rs").write_text(
        "use counter_rust::{CounterState, counter_increment};\n\n"
        "#[test]\nfn test_counter() {\n"
        "    let mut state = CounterState { value: 0 };\n"
        "    let observed = counter_increment(&mut state, 1);\n"
        "    assert_eq!(observed, 1);\n"
        "    assert_eq!(state.value, 1);\n"
        "}\n",
        encoding="utf-8",
    )
    return project


def _trace_with_generation(root):
    trace = root / "trace"
    source = build_complete_analysis(_packet(FIXTURE), _legacy(FIXTURE))
    if not source["verification"]["passed"]:
        raise AssertionError(source["verification"])
    write_complete_analysis(source, trace)
    plan = build_semantic_plan(load_analysis_evidence(trace), run_id="planning-run")
    write_semantic_plan(plan, trace)
    _write_coverage(trace)
    project = _project(root)
    generation_inputs = load_generation_inputs(trace)
    generation = build_generation_evidence(project, generation_inputs, run_id="generation-run", build=True)
    if not generation["verification"]["passed"]:
        raise AssertionError(generation["verification"])
    write_generation_evidence(generation, trace)
    return trace, project


class TestMigrationValidationTests(unittest.TestCase):
    def test_schema_contracts_and_coherent_loader(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
        self.assertEqual(inputs["source_tests"][0]["file"], "tests/test_counter.c")
        self.assertEqual(len(inputs["invariants"]), 1)
        self.assertTrue(inputs["implementation_ids"])

    def test_loader_rejects_negative_evidence_fixtures(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); trace, project = _trace_with_generation(root)
            doc = json.loads((trace / "generation-verification.json").read_text())
            doc["run_id"] = "stale"
            (trace / "generation-verification.json").write_text(json.dumps(doc))
            with self.assertRaises(TestValidationBlocked) as caught:
                load_validation_inputs(trace, project)
            self.assertIn("mixed_generation_run_ids", caught.exception.failures)

        for edit, expected in [
            (lambda trace: (trace / "01f-test-coverage-map.json").write_text(json.dumps({"source_tests": []})), "empty_denominator:source_tests"),
            (lambda trace: (trace / "01f-test-coverage-map.json").write_text(json.dumps({"source_tests": [{"file": "tests/test_counter.c", "assertions": []}]})), "empty_denominator:source_assertions"),
            (lambda trace: _replace_json(trace / "semantic-invariants.json", "invariants", []), "empty_denominator:semantic_invariants"),
            (lambda trace: _replace_json(trace / "implementation-map.json", "implementations", []), "missing_implementation_ids"),
        ]:
            with tempfile.TemporaryDirectory() as temp:
                trace, project = _trace_with_generation(Path(temp))
                edit(trace)
                with self.assertRaises(TestValidationBlocked) as caught:
                    load_validation_inputs(trace, project)
                self.assertIn(expected, caught.exception.failures)

    def test_non_project_fixture_uses_same_pipeline_and_counting_rules(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            vectors = build_differential_vectors(inputs)
            cargo = {"executed_test_count": 1}
            counts = canonical_counts({**inputs, "differential_vectors": vectors, "cargo_test": cargo})
        self.assertEqual(counts["source_test_count"], 1)
        self.assertEqual(counts["source_assertion_count"], 1)
        self.assertEqual(counts["semantic_invariant_count"], 1)
        self.assertEqual(counts["differential_scenario_count"], 1)

    def test_test_ir_source_maps_and_invariant_maps_are_complete(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            assertion_scan = scan_assertions(project)
            test_ir = build_test_ir(inputs)
            source_map = build_source_test_map(inputs, test_ir, assertion_scan)
            vectors = build_differential_vectors(inputs)
            invariant_map = build_invariant_test_map(inputs, assertion_scan, vectors)
        self.assertEqual(len(test_ir["cases"]), 1)
        self.assertEqual(source_map["metrics"]["mapped_source_test_count"], 1)
        self.assertEqual(invariant_map["metrics"]["covered_invariant_count"], 1)

    def test_unmigratable_and_weakened_assertions_are_blocking_diagnostics(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            broken = copy.deepcopy(inputs)
            broken["source_tests"][0]["referenced_apis"] = ["missing_api"]
            test_ir = build_test_ir(broken)
            source_map = build_source_test_map(broken, test_ir, {"effective_assertions": []})
            weakened = detect_weakened_assertions(source_map, {"effective_assertions": []})
        self.assertEqual(test_ir["diagnostics"][0]["code"], "referenced_api_without_implementation")
        self.assertTrue(any(item["code"] == "source_assertion_effect_removed" for item in weakened))

    def test_assertion_scanner_rejects_vacuous_self_match_empty_and_ignored_tests(self):
        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp); (project / "tests").mkdir()
            (project / "tests" / "bad.rs").write_text(
                "#[test]\nfn a() { assert!(true); }\n"
                "#[test]\nfn b() { let x = 1; assert_eq!(x, x); }\n"
                "#[test]\nfn c() { assert!(matches!(x, _)); }\n"
                "#[test]\nfn d() { }\n"
                "#[ignore]\n#[test]\nfn e() { assert_ne!(1, 2); }\n",
                encoding="utf-8",
            )
            scan = scan_assertions(project)
        kinds = {item["kind"] for item in scan["findings"]}
        self.assertTrue({"assert_true", "assert_eq_self", "assert_matches_wildcard", "empty_test", "ignored_test"} <= kinds)
        self.assertFalse(scan["passed"])

    def test_differential_vectors_execution_and_mismatches(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            vectors = build_differential_vectors(inputs)
            passed = execute_differential_vectors(vectors)
            failed = execute_differential_vectors(vectors, force_difference={"return_value": {"different": True}})
            c_failed = execute_differential_vectors(vectors, fail_side="c")
        self.assertTrue(passed["passed"])
        self.assertFalse(failed["passed"])
        self.assertEqual(failed["failures"][0]["reason"], "comparison_mismatch")
        self.assertFalse(c_failed["passed"])

    def test_state_machine_and_mutation_testing_gates(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            state_vectors = build_state_machine_vectors(inputs)
            mutation_pass = run_mutation_testing()
            mutation_fail = run_mutation_testing(detected=set(FIXED_MUTATIONS) - {"wrong_return_code"})
        self.assertTrue(state_vectors)
        self.assertTrue(mutation_pass["passed"])
        self.assertFalse(mutation_fail["passed"])
        self.assertEqual(mutation_fail["survivors"][0]["mutation_id"], "wrong_return_code")

    def test_project_customization_scanner_detects_control_flow_and_allows_data(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            bad = root / "bad.py"
            good = root / "report.md"
            bad.write_text('if project_name == "counter":\n    use_golden_output()\n', encoding="utf-8")
            good.write_text("- source symbol: counter_increment\n", encoding="utf-8")
            report = scan_project_customization([bad, good], ["counter", "counter_increment"])
        self.assertFalse(report["passed"])
        self.assertEqual(report["findings"][0]["line"], 1)
        self.assertEqual(report["adjudications"][0]["verdict"], "input-evidence-or-report-data")

    def test_project_terms_come_from_inputs_not_hardcoded_identity(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            terms = project_terms_from_inputs(inputs)
        self.assertIn("counter_increment", terms)
        self.assertNotIn("kvdb", " ".join(terms).lower())

    def test_cargo_test_execution_and_zero_test_rejection(self):
        with tempfile.TemporaryDirectory() as temp:
            project = _project(Path(temp))
            result = run_cargo_tests(project)
        self.assertTrue(result["passed"], result["stderr"])
        self.assertGreater(result["executed_test_count"], 0)

        with tempfile.TemporaryDirectory() as temp:
            project = Path(temp); (project / "src").mkdir()
            (project / "Cargo.toml").write_text('[package]\nname="empty"\nversion="0.1.0"\nedition="2021"\n')
            (project / "Cargo.lock").write_text('# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "empty"\nversion = "0.1.0"\n')
            (project / "src" / "lib.rs").write_text("pub fn value() -> i32 { 1 }\n")
            result = run_cargo_tests(project)
        self.assertFalse(result["passed"])
        self.assertEqual(result["executed_test_count"], 0)

    def test_full_validation_and_atomic_publication(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); trace, project = _trace_with_generation(root)
            inputs = load_validation_inputs(trace, project)
            validation = validate_all(inputs, project, run_cargo=False)
            bundle = build_evidence(inputs, project, run_cargo=False)
            out = root / "out"
            write_evidence(bundle, out)
            before = {name: (out / name).read_bytes() for name in OUTPUT_FILES}
            broken = copy.deepcopy(bundle)
            del broken["artifacts"][OUTPUT_FILES[0]]
            with self.assertRaises(KeyError):
                write_evidence(broken, out)
            self.assertEqual(before, {name: (out / name).read_bytes() for name in OUTPUT_FILES})
        self.assertTrue(validation["passed"], validation["failures"])

    def test_validation_blocks_customization_vacuous_differential_and_survivor(self):
        with tempfile.TemporaryDirectory() as temp:
            trace, project = _trace_with_generation(Path(temp))
            inputs = load_validation_inputs(trace, project)
            (project / "tests" / "source_migration.rs").write_text("#[test]\nfn bad() { assert!(true); }\n")
            validation = validate_all(inputs, project, run_cargo=False)
        self.assertFalse(validation["checks"]["assertion_scan_clear"])

        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); trace, project = _trace_with_generation(root)
            inputs = load_validation_inputs(trace, project)
            bad = root / "bad.py"; bad.write_text('if name == "counter_increment": pass\n')
            validation = validate_all(inputs, project, run_cargo=False, customization_paths=[bad])
        self.assertFalse(validation["checks"]["anti_customization_passed"])


def _replace_json(path, key, value):
    doc = json.loads(path.read_text())
    doc[key] = value
    path.write_text(json.dumps(doc))


if __name__ == "__main__":
    unittest.main()
